
version: "3.3"
services:
  app:
    image: node:8.9-alpine
    container_name: pubsub-demo
    working_dir: /app
    volumes:
      - ./:/app
    ports:
     - "4000:4000"
    depends_on:
      - "gcloud-pubsub"
    environment:
      PUBSUB_EMULATOR_HOST: gcloud-pubsub:8085
      PUBSUB_PROJECT_ID: pubsub-demo
  gcloud-pubsub:
    image: sweetiq/gcloud-pubsub-emulator:198.0.0
    container_name: gcloud-pubsub


networks:
  default:
    external:
      name: pubsub-net